language: go

go:
  - "1.8.x"
  - "1.9.x"
  - "1.10.x"
  - tip

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

install:
  - go get golang.org/x/text/encoding
  - go get golang.org/x/net/context
  - go get github.com/stretchr/testify/assert

os:
  - linux

script:
  - base=$(echo $PWD | sed "s|$GOPATH/src/||") && go test -race -v $(go list ./... | grep -v vendor | sed "s|$base/|./|")
  - $GOPATH/bin/goveralls -service=travis-ci
